services: 
  python:
    build: ./
    container_name: sh_python
    volumes:
      - type: bind
        source: ./src/
        target: /var/www/src
    restart: always
    tty: true

  db:
    image: postgres:17.6-alpine
    container_name: sh_db
    environment:
      POSTGRES_USER: sh_user
      POSTGRES_PASSWORD: sh_password
      POSTGRES_DB: sh_db
    